
package complaint.Employee;

import DBConnection.connection;
import FeedbackAndComments.CommentDisplay;
import FeedbackAndComments.FeedbackAndCommentsDisplay;
import homepage.Homepage;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logs.loggWriter;

/**
 *
 * @author rishabh kumar
 */
public class EmployeeMenu extends javax.swing.JFrame {
    connection c=new connection();
    String eid;
    /**
     * Creates new form EmployeeMenu
     */
    public EmployeeMenu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        new loggWriter("Employee Menu Opened.",true);
    }

    EmployeeMenu(String string) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        new loggWriter("Employee Menu Opened.",true);
        eid=string;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pendingComplaint = new javax.swing.JLabel();
        FeedbackAndComments = new javax.swing.JLabel();
        comment = new javax.swing.JLabel();
        searchCustomer = new javax.swing.JLabel();
        homepage = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Employee Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 20, 660, 70);

        pendingComplaint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeAssets/PendingComplaint.jpg"))); // NOI18N
        pendingComplaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingComplaintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pendingComplaintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pendingComplaintMouseExited(evt);
            }
        });
        jPanel1.add(pendingComplaint);
        pendingComplaint.setBounds(40, 110, 230, 230);

        FeedbackAndComments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeAssets/draw3.jpg"))); // NOI18N
        FeedbackAndComments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedbackAndCommentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FeedbackAndCommentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FeedbackAndCommentsMouseExited(evt);
            }
        });
        jPanel1.add(FeedbackAndComments);
        FeedbackAndComments.setBounds(40, 430, 230, 230);

        comment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeAssets/comment.jpg"))); // NOI18N
        comment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commentMouseExited(evt);
            }
        });
        jPanel1.add(comment);
        comment.setBounds(1010, 430, 240, 230);

        searchCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeAssets/SearchCustomer.jpg"))); // NOI18N
        searchCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchCustomerMouseExited(evt);
            }
        });
        jPanel1.add(searchCustomer);
        searchCustomer.setBounds(1010, 110, 240, 230);

        homepage.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        homepage.setForeground(new java.awt.Color(204, 204, 204));
        homepage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/homepage.png"))); // NOI18N
        homepage.setToolTipText("Back to Homepage");
        homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homepageMouseExited(evt);
            }
        });
        jPanel1.add(homepage);
        homepage.setBounds(100, 30, 80, 60);

        close.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        close.setForeground(new java.awt.Color(204, 204, 204));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cancel.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(1080, 30, 80, 60);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dribbb.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 80, 1280, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseClicked
        Homepage home=new Homepage();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homepageMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void pendingComplaintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingComplaintMouseClicked
        PendingComplaint pending=new PendingComplaint(eid);
        pending.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pendingComplaintMouseClicked

    private void commentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseClicked
        CommentDisplay cd=new CommentDisplay();
        cd.setVisible(true);
    }//GEN-LAST:event_commentMouseClicked

    private void searchCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCustomerMouseClicked
        String cid=JOptionPane.showInputDialog("Enter CustomerID :");
        try {
            c.rs=c.stmt.executeQuery("Select cid from Customerlogin where cid='"+cid+"';");
            if(c.rs.next()){
                CustomerDetails details=new CustomerDetails(c.rs.getString("cid"));
                details.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(null, "No Suc Record Found. Check Your Customer ID.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "An Error Occured.\nError Description - "+ex);
        }
    }//GEN-LAST:event_searchCustomerMouseClicked

    private void FeedbackAndCommentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackAndCommentsMouseClicked
       FeedbackAndCommentsDisplay display=new FeedbackAndCommentsDisplay();
       display.setVisible(true);
    }//GEN-LAST:event_FeedbackAndCommentsMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int option;
        option=JOptionPane.showConfirmDialog(this, "Confirm To Exit?", "Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(option==0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void pendingComplaintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingComplaintMouseEntered
        pendingComplaint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_pendingComplaintMouseEntered

    private void pendingComplaintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingComplaintMouseExited
        pendingComplaint.setBorder(null);
    }//GEN-LAST:event_pendingComplaintMouseExited

    private void searchCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCustomerMouseEntered
       searchCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_searchCustomerMouseEntered

    private void searchCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchCustomerMouseExited
        searchCustomer.setBorder(null);
    }//GEN-LAST:event_searchCustomerMouseExited

    private void FeedbackAndCommentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackAndCommentsMouseEntered
        FeedbackAndComments.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_FeedbackAndCommentsMouseEntered

    private void FeedbackAndCommentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackAndCommentsMouseExited
        FeedbackAndComments.setBorder(null);
    }//GEN-LAST:event_FeedbackAndCommentsMouseExited

    private void commentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseEntered
        comment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_commentMouseEntered

    private void commentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseExited
      comment.setBorder(null);
    }//GEN-LAST:event_commentMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_closeMouseEntered

    private void homepageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseEntered
        homepage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_homepageMouseEntered

    private void homepageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseExited
       homepage.setBorder(null);
    }//GEN-LAST:event_homepageMouseExited

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBorder(null);
    }//GEN-LAST:event_closeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FeedbackAndComments;
    private javax.swing.JLabel close;
    private javax.swing.JLabel comment;
    private javax.swing.JLabel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pendingComplaint;
    private javax.swing.JLabel searchCustomer;
    // End of variables declaration//GEN-END:variables
}
