
package complaint.Employee;

import DBConnection.connection;
import homepage.Homepage;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logs.loggWriter;

/**
 *
 * @author rishabh kumar
 */
public class PendingComplaint extends javax.swing.JFrame {
connection c=new connection();
    String EID;
            DefaultListModel dlm=new DefaultListModel();
    /**
     * Creates new form pendingComplaint
     */
    public PendingComplaint() {
        initComponents();
    }

    PendingComplaint(String eid) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        new loggWriter("Pending Complaint Opened.",true);
        try {
        
        EID=eid;

        c.rs=c.stmt.executeQuery("select cid from complaintRegistration where status!='completed';");
        if(c.rs.isBeforeFirst()){
            
          dlm.addElement("Select-----");
            while(true)
                if(c.rs.next())
                    dlm.addElement(c.rs.getString("cid"));
                else
                    break;}
        else
            dlm.addElement("<Empty List>");
        cid.setModel(dlm);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Complaint List Loading Error\nError Description - "+ex);
        new logs.loggWriter().write2( "Complaint List Loading Error\nError Description - "+ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cdescription = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cid = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        complaintAction = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        homepage = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pending Complaints");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 30, 680, 80);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jPanel4);
        jPanel4.setBounds(400, 180, 10, 410);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jPanel5);
        jPanel5.setBounds(830, 180, 10, 410);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(null);

        cdescription.setEditable(false);
        cdescription.setColumns(20);
        cdescription.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        cdescription.setRows(5);
        jScrollPane2.setViewportView(cdescription);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(20, 80, 320, 260);

        jLabel15.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Complaint Description");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(37, 30, 280, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/wp2533040.jpg"))); // NOI18N
        jPanel7.add(jLabel16);
        jLabel16.setBounds(10, 10, 340, 340);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(880, 190, 360, 360);

        cid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cid.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Cid-00000aaa", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        cid.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cidMouseExited(evt);
            }
        });
        cid.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                cidValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(cid);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 230, 240, 320);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Select Product ID :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 160, 260, 50);

        complaintAction.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        complaintAction.setForeground(new java.awt.Color(204, 204, 204));
        complaintAction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        complaintAction.setText("Complaint Action");
        complaintAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complaintActionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                complaintActionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                complaintActionMouseExited(evt);
            }
        });
        jPanel1.add(complaintAction);
        complaintAction.setBounds(400, 620, 440, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Customer's Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 200, 280, 40);

        cname.setEditable(false);
        cname.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel1.add(cname);
        cname.setBounds(480, 280, 280, 40);

        title.setEditable(false);
        title.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jPanel1.add(title);
        title.setBounds(440, 440, 360, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Problem Title :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 360, 280, 40);

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit(2).png"))); // NOI18N
        exit.setToolTipText("Feeling bored? Exit !");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(1130, 640, 110, 60);

        homepage.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        homepage.setForeground(new java.awt.Color(204, 204, 204));
        homepage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/homepage.png"))); // NOI18N
        homepage.setToolTipText("Back to Homepage");
        homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homepageMouseExited(evt);
            }
        });
        jPanel1.add(homepage);
        homepage.setBounds(90, 630, 80, 60);

        back.setFont(new java.awt.Font("Bauhaus 93", 1, 48)); // NOI18N
        back.setForeground(new java.awt.Color(204, 204, 204));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("<<");
        back.setToolTipText("Admin Menu");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(60, 50, 150, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/wp2533040.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cidValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_cidValueChanged
        cdescription.setText(null);
        if(cid.getSelectedValue().equals("<Empty List>")){
            JOptionPane.showMessageDialog(null, "No Current Pending Complaints Found. Come Back Later.");
        }
        else{
            try {
                c.rs=c.stmt.executeQuery("Select cr.cid,complaint_id,cname,ProblemTitle,description,status,TypeOfService from complaintregistration cr inner join customer c on c.cid=cr.cid where cr.cid='"
                +cid.getSelectedValue()+"';");
                if(c.rs.next()){
                    cname.setText(c.rs.getString("cname"));
                    title.setText(c.rs.getString("ProblemTitle"));
                    cdescription.append("Complaint ID - "+c.rs.getString("Complaint_id")+"\nDescription - "+c.rs.getString("description")+"\nStatus - "
                            +c.rs.getString("status")+"\nType Of Service - "+c.rs.getString("TypeOfService"));
                }
                else
                    JOptionPane.showMessageDialog(null, "Record Not Found.");
            } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "An Error Ocurred While Connecting To the Database.\nError Description - "+ex);
            }
        }
    }//GEN-LAST:event_cidValueChanged

    private void complaintActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintActionMouseClicked
        ComplaintAction action=null;
        if(cid.getSelectedIndex()!=0)
            action=new ComplaintAction(cid.getSelectedValue().toString(),EID);
        action.setVisible(true);
    }//GEN-LAST:event_complaintActionMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        int a;
        a = JOptionPane.showConfirmDialog(null,"Feeling Bored?? Wanna Exit?","Please Don't Leave.",JOptionPane.YES_NO_CANCEL_OPTION);
        if(a==0){
            JOptionPane.showMessageDialog(null, "I'll Miss YOU!!", "Miss You.", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
        else if(a==1||a==2){
            JOptionPane.showMessageDialog(null,"I Love You Tooo!!!!","hehe.", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseClicked
        Homepage home=new Homepage();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homepageMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        EmployeeMenu emenu=new EmployeeMenu();
        emenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int option;
        option=JOptionPane.showConfirmDialog(this, "Confirm To Exit?", "Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(option==0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBorder(null);
    }//GEN-LAST:event_backMouseExited

    private void homepageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseEntered
       homepage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_homepageMouseEntered

    private void homepageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseExited
       homepage.setBorder(null);
    }//GEN-LAST:event_homepageMouseExited

    private void complaintActionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintActionMouseEntered
       complaintAction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_complaintActionMouseEntered

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_exitMouseEntered

    private void complaintActionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintActionMouseExited
        complaintAction.setBorder(null);
    }//GEN-LAST:event_complaintActionMouseExited

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
       exit.setBorder(null);
    }//GEN-LAST:event_exitMouseExited

    private void cidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cidMouseEntered
        cid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_cidMouseEntered

    private void cidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cidMouseExited
        cid.setBorder(null);
    }//GEN-LAST:event_cidMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingComplaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTextArea cdescription;
    private javax.swing.JList cid;
    private javax.swing.JTextField cname;
    private javax.swing.JLabel complaintAction;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
