
package homepage;

import Admin.AdminLogin;
import complaint.Employee.EmployeeLogin;
import customer.CustomerLogin;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logs.loggWriter;


public class Homepage extends javax.swing.JFrame {


    public Homepage() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        new loggWriter("Homepage Opened.",true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Adminlogin = new javax.swing.JLabel();
        Customerlogin = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        Employeelogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Homepage");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Complaint Management System");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(50, 20, 1170, 70);

        Adminlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomepageAssets/AdminLogin.jpg"))); // NOI18N
        Adminlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminloginMouseExited(evt);
            }
        });
        jPanel3.add(Adminlogin);
        Adminlogin.setBounds(40, 160, 230, 220);

        Customerlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomepageAssets/CustomerLogin.jpg"))); // NOI18N
        Customerlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CustomerloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CustomerloginMouseExited(evt);
            }
        });
        jPanel3.add(Customerlogin);
        Customerlogin.setBounds(40, 440, 230, 230);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomepageAssets/Exit.jpg"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel3.add(exit);
        exit.setBounds(1010, 440, 240, 230);

        Employeelogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomepageAssets/EmployeeLogin.jpg"))); // NOI18N
        Employeelogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeloginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeloginMouseExited(evt);
            }
        });
        jPanel3.add(Employeelogin);
        Employeelogin.setBounds(1010, 160, 240, 220);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dribbb.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 100, 1280, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeloginMouseClicked
       EmployeeLogin elogin=new EmployeeLogin();
        elogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EmployeeloginMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        int option;
        option=JOptionPane.showConfirmDialog(this, "Confirm To Exit?", "Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(option==0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void AdminloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminloginMouseClicked
        Adminlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AdminLogin alogin=new AdminLogin();
        alogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminloginMouseClicked

    private void CustomerloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerloginMouseClicked
        Customerlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CustomerLogin clogin=new CustomerLogin();
        clogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CustomerloginMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int option;
        option=JOptionPane.showConfirmDialog(this, "Confirm To Exit?", "Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(option==0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void AdminloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminloginMouseEntered
        Adminlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_AdminloginMouseEntered

    private void AdminloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminloginMouseExited
       Adminlogin.setBorder(null);
    }//GEN-LAST:event_AdminloginMouseExited

    private void EmployeeloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeloginMouseEntered
         Employeelogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_EmployeeloginMouseEntered

    private void EmployeeloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeloginMouseExited
        Employeelogin.setBorder(null);
    }//GEN-LAST:event_EmployeeloginMouseExited

    private void CustomerloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerloginMouseEntered
        Customerlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_CustomerloginMouseEntered

    private void CustomerloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerloginMouseExited
        Customerlogin.setBorder(null);
    }//GEN-LAST:event_CustomerloginMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBorder(null);
    }//GEN-LAST:event_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adminlogin;
    private javax.swing.JLabel Customerlogin;
    private javax.swing.JLabel Employeelogin;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
