
package customer;

import DBConnection.connection;
import FeedbackAndComments.Comments;
import complaint.Customer.ComplaintRegistration;
import homepage.Homepage;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logs.loggWriter;

/**
 *
 * @author rishabh kumar
 */
public class CustomerMenu extends javax.swing.JFrame {
    String cid;
    connection c=new connection();
    /**
     * Creates new form CustomerMenu
     */
    public CustomerMenu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        new loggWriter("Customer Menu Opened.",true);
    }

    CustomerMenu(String string) {
        initComponents();
        cid=string;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        new loggWriter("Customer Menu Opened.",true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        complaintRegistration = new javax.swing.JLabel();
        complaintStatus = new javax.swing.JLabel();
        comment = new javax.swing.JLabel();
        editDetail = new javax.swing.JLabel();
        homepage = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer Menu");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 20, 660, 70);

        complaintRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customerAssets/complaintRegistration.jpg"))); // NOI18N
        complaintRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complaintRegistrationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                complaintRegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                complaintRegistrationMouseExited(evt);
            }
        });
        jPanel1.add(complaintRegistration);
        complaintRegistration.setBounds(1010, 100, 240, 260);

        complaintStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customerAssets/complaintStatus.jpg"))); // NOI18N
        complaintStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complaintStatusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                complaintStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                complaintStatusMouseExited(evt);
            }
        });
        jPanel1.add(complaintStatus);
        complaintStatus.setBounds(40, 420, 230, 260);

        comment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customerAssets/comment.jpg"))); // NOI18N
        comment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commentMouseExited(evt);
            }
        });
        jPanel1.add(comment);
        comment.setBounds(1010, 420, 240, 260);

        editDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customerAssets/editDetails.jpg"))); // NOI18N
        editDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editDetailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editDetailMouseExited(evt);
            }
        });
        jPanel1.add(editDetail);
        editDetail.setBounds(40, 100, 240, 260);

        homepage.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        homepage.setForeground(new java.awt.Color(204, 204, 204));
        homepage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/homepage.png"))); // NOI18N
        homepage.setToolTipText("Back to Homepage");
        homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homepageMouseExited(evt);
            }
        });
        jPanel1.add(homepage);
        homepage.setBounds(100, 30, 80, 60);

        close.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        close.setForeground(new java.awt.Color(204, 204, 204));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cancel.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(1150, 30, 70, 60);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dribbb.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 80, 1280, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        new tts.TextToSpeech().mySpeak("Customer Menu.");
    }//GEN-LAST:event_jLabel2MouseEntered

    private void editDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editDetailMouseClicked
       CustomerDetail detail=new CustomerDetail(cid);
        detail.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editDetailMouseClicked

    private void complaintRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintRegistrationMouseClicked
        ComplaintRegistration regist=new ComplaintRegistration(cid);
        regist.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_complaintRegistrationMouseClicked

    private void complaintStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintStatusMouseClicked
        try {
            c.rs=c.stmt.executeQuery("Select cid from complaintRegistration where cid='"+cid+"';");
        
        if(c.rs.isBeforeFirst()){
        ComplaintDetails details=new ComplaintDetails(cid);
        details.setVisible(true);
        this.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(null, "You Have Not Filed Any Complaint Yet. \nTry Selecting Complaint Registration Option.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "A n Error Occured.\nError Description - "+ex);
        }
    }//GEN-LAST:event_complaintStatusMouseClicked

    private void commentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseClicked
       Comments com=new Comments();
       com.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_commentMouseClicked

    private void homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseClicked
        Homepage home=new Homepage();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homepageMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int option;
        option=JOptionPane.showConfirmDialog(this, "Confirm To Exit?", "Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(option==0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void homepageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseEntered
        homepage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_homepageMouseEntered

    private void homepageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseExited
        homepage.setBorder(null);
    }//GEN-LAST:event_homepageMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
       close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBorder(null);
    }//GEN-LAST:event_closeMouseExited

    private void editDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editDetailMouseEntered
       editDetail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_editDetailMouseEntered

    private void editDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editDetailMouseExited
        editDetail.setBorder(null);
    }//GEN-LAST:event_editDetailMouseExited

    private void complaintRegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintRegistrationMouseEntered
       complaintRegistration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_complaintRegistrationMouseEntered

    private void complaintRegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintRegistrationMouseExited
       complaintRegistration.setBorder(null);
    }//GEN-LAST:event_complaintRegistrationMouseExited

    private void complaintStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintStatusMouseExited
        complaintStatus.setBorder(null);
    }//GEN-LAST:event_complaintStatusMouseExited

    private void complaintStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintStatusMouseEntered
        complaintStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_complaintStatusMouseEntered

    private void commentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseEntered
        comment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_commentMouseEntered

    private void commentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseExited
       comment.setBorder(null);
    }//GEN-LAST:event_commentMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel comment;
    private javax.swing.JLabel complaintRegistration;
    private javax.swing.JLabel complaintStatus;
    private javax.swing.JLabel editDetail;
    private javax.swing.JLabel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
