
package Admin;

import FeedbackAndComments.FeedbackAndCommentsDisplay;
import homepage.Homepage;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author rishabh kumar
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addEngineer = new javax.swing.JLabel();
        SearchEngineer = new javax.swing.JLabel();
        FnC = new javax.swing.JLabel();
        terminateEngineer = new javax.swing.JLabel();
        homepage = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Menu");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Admin Menu");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 20, 660, 70);

        addEngineer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminAssets/addEngineer.jpg"))); // NOI18N
        addEngineer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEngineerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEngineerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEngineerMouseExited(evt);
            }
        });
        jPanel1.add(addEngineer);
        addEngineer.setBounds(40, 100, 230, 260);

        SearchEngineer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminAssets/SearchEngineer.jpg"))); // NOI18N
        SearchEngineer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchEngineerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchEngineerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchEngineerMouseExited(evt);
            }
        });
        jPanel1.add(SearchEngineer);
        SearchEngineer.setBounds(40, 420, 230, 260);

        FnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminAssets/feedbackAndComments.jpg"))); // NOI18N
        FnC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FnCMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FnCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FnCMouseExited(evt);
            }
        });
        jPanel1.add(FnC);
        FnC.setBounds(1010, 420, 240, 260);

        terminateEngineer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AdminAssets/TerminatingEngineer.jpg"))); // NOI18N
        terminateEngineer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terminateEngineerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                terminateEngineerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                terminateEngineerMouseExited(evt);
            }
        });
        jPanel1.add(terminateEngineer);
        terminateEngineer.setBounds(1010, 100, 240, 260);

        homepage.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        homepage.setForeground(new java.awt.Color(204, 204, 204));
        homepage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/homepage.png"))); // NOI18N
        homepage.setToolTipText("Back to Homepage");
        homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homepageMouseExited(evt);
            }
        });
        jPanel1.add(homepage);
        homepage.setBounds(130, 30, 70, 60);

        exit.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 204, 204));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cancel.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(1100, 30, 70, 60);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dribbb.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 80, 1280, 640);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        new tts.TextToSpeech().mySpeak("Admin Menu.");
    }//GEN-LAST:event_jLabel2MouseEntered

    private void homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseClicked
        Homepage home=new Homepage();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homepageMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void addEngineerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEngineerMouseClicked
        NewEmployee add=new NewEmployee();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addEngineerMouseClicked

    private void terminateEngineerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminateEngineerMouseClicked
       TerminatingEmployee terminate=new TerminatingEmployee();
        terminate.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_terminateEngineerMouseClicked

    private void SearchEngineerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchEngineerMouseClicked
       SearchEmployee search=new SearchEmployee();
        search.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SearchEngineerMouseClicked

    private void FnCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FnCMouseClicked
       FeedbackAndCommentsDisplay feecom=new FeedbackAndCommentsDisplay();
       feecom.setVisible(true);
    }//GEN-LAST:event_FnCMouseClicked

    private void homepageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseEntered
        homepage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_homepageMouseEntered

    private void homepageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageMouseExited
       homepage.setBorder(null);
    }//GEN-LAST:event_homepageMouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setBorder(null);
    }//GEN-LAST:event_exitMouseExited

    private void addEngineerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEngineerMouseEntered
        addEngineer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_addEngineerMouseEntered

    private void addEngineerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEngineerMouseExited
        addEngineer.setBorder(null);
    }//GEN-LAST:event_addEngineerMouseExited

    private void terminateEngineerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminateEngineerMouseEntered
        terminateEngineer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_terminateEngineerMouseEntered

    private void terminateEngineerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminateEngineerMouseExited
       terminateEngineer.setBorder(null);
    }//GEN-LAST:event_terminateEngineerMouseExited

    private void SearchEngineerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchEngineerMouseEntered
        SearchEngineer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_SearchEngineerMouseEntered

    private void SearchEngineerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchEngineerMouseExited
        SearchEngineer.setBorder(null);
    }//GEN-LAST:event_SearchEngineerMouseExited

    private void FnCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FnCMouseEntered
       FnC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.SoftBevelBorder.RAISED));
    }//GEN-LAST:event_FnCMouseEntered

    private void FnCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FnCMouseExited
        FnC.setBorder(null);
    }//GEN-LAST:event_FnCMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int option;
        option=JOptionPane.showConfirmDialog(this, "Confirm To Exit?", "Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(option==0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FnC;
    private javax.swing.JLabel SearchEngineer;
    private javax.swing.JLabel addEngineer;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel homepage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel terminateEngineer;
    // End of variables declaration//GEN-END:variables
}
